- name: create /home/opc/ha_config directory
  become: true
  file:
    path: /home/opc/ha_config
    state: directory

- name: create corosync file
  template:
    src: _corosync.j2
    dest: /home/opc/ha_config/corosync

- name: create corosync.conf with 1 ring
  template:
    src: _corosync.conf.1ring.j2
    dest: /home/opc/ha_config/corosync.conf

- name: create logrotate.d corosync file
  template:
    src: _logrotate.d_corosync.j2
    dest: /etc/logrotate.d/corosync
    force: true
    backup: true
    owner: root
    group: root
    mode: 0644

# only for VMs - since they come up too quickly before stonith fencing completes.
- name: add 30s delay for VM instances for corosync service
  lineinfile:
    path: /usr/lib/systemd/system/corosync.service
    insertbefore: 'ExecStart=/usr/share/corosync/corosync start'
    line: 'ExecStartPre=/bin/sleep 30'
    state: present
    create: no
  when: (fs_ha|bool and (not {{ storage_server_dual_nics }}))|default(false)|bool